var res = {
    HelloWorld_png : "res/HelloWorld.png",
    menu_titulo_png : "res/menu_titulo.png",
    boton_jugar_png : "res/boton_jugar.png",
    tiles16_png: "res/tiles16.png",
    mapa1_tmx: "res/mapa1.tmx",
    caballero_png: "res/caballero.png",
    caballero_plist: "res/caballero.plist",
    caballero_ataque_png: "res/caballero_ataque.png",
    caballero_ataque_plist: "res/caballero_ataque.plist",
    caballero_muerte_png: "res/caballero_muerte.png",
    caballero_muerte_plist: "res/caballero_muerte.plist",
    arquero_png: "res/arquero.png",
    arquero_plist: "res/arquero.plist",
    arquero_ataque_png: "res/arquero_ataque.png",
    arquero_ataque_plist: "res/arquero_ataque.plist",
    arquero_muerte_png: "res/arquero_muerte.png",
    arquero_muerte_plist: "res/arquero_muerte.plist",
    flecha_png: "res/flecha.png",
    flecha_plist: "res/flecha.plist",
    piedra_png: "res/piedra.png",
    rey_png: "res/rey.png",
    rey_plist: "res/rey.plist",
    rey_muerte_png: "res/rey_muerte.png",
    rey_muerte_plist: "res/rey_muerte.plist",
    moneda_png : "res/monedas.png",
    moneda_plist : "res/monedas.plist",
    inmunidad_png: "res/inmunidad.png",
    inmunidad_plist: "res/inmunidad.plist",
    corazon_png: "res/corazon.png",
    meta_png: "res/meta.png",
    victoria_png: "res/victoria.png",
    derrota_png: "res/derrota.png",
    caja_madera_png: "res/caja_madera.png",
    caja_metal_png: "res/caja_metal.png",
    puerta_abierta_png: "res/puerta_abierta.png",
    puerta_cerrada_png: "res/puerta_cerrada.png",
    hud_corazon_png: "res/hud_corazon.png",
    hud_moneda_png: "res/hud_moneda.png",

    musica_fondo_wav: "res/raw/musica_fondo.wav",
    ataque_espada_wav: "res/raw/ataque_espada.wav",
    impacto_espada_wav: "res/raw/impacto_espada.wav",
    lanzamiento_flecha_piedra_wav: "res/raw/lanzamiento_flecha_piedra.wav",
    impacto_flecha_wav: "res/raw/impacto_flecha.wav",
    rebote_piedra_wav: "res/raw/rebote_piedra.wav",
    corazon_recogido_wav: "res/raw/corazon_recogido.wav",
    moneda_recogida_wav: "res/raw/moneda_recogida.wav",
    inmunidad_recogido_wav: "res/raw/inmunidad_recogido.wav",
    caballero_golpeado_wav: "res/raw/caballero_golpeado.wav",
    caballero_muriendo_wav: "res/raw/caballero_muriendo.wav",
    enemigo_muriendo_wav: "res/raw/enemigo_muriendo.wav",
    meta_aparece_wav: "res/raw/meta_aparece.wav",
    recogiendo_meta_wav: "res/raw/recogiendo_meta.wav",
    puerta_wav: "res/raw/puerta.wav",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}